name: telegram message

on:

  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: 7549151423:AAHDeCkAOc9idbYAIM1ehO3ulqJ7kXMmEP0
          message: |
            Колмаков Петухов
          
